// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block              = require("bs-platform/lib/js/block.js");
var React              = require("react");
var ReasonReact        = require("reason-react/src/ReasonReact.js");
var Nice$ReactTemplate = require("../Nice.bs.js");

var buttonStyle = Nice$ReactTemplate.css(/* :: */[
      /* FontWeight */Block.__(70, [/* Bold */1]),
      /* :: */[
        /* BorderWidth */Block.__(26, [/* Px */Block.__(0, [0])]),
        /* :: */[
          /* Color */Block.__(66, [/* RGBa */Block.__(1, [
                  67,
                  90,
                  111,
                  0.845
                ])]),
          /* :: */[
            /* BackgroundImage */Block.__(52, ["linear-gradient(to top, rgba(67,90,111,0.114), rgba(67,90,111,0.041))"]),
            /* :: */[
              /* Cursor */Block.__(2, [/* Pointer */0]),
              /* :: */[
                /* Padding */Block.__(19, [/* Em */Block.__(1, [0.75])]),
                /* :: */[
                  /* PaddingRight */Block.__(25, [/* Em */Block.__(1, [2.0])]),
                  /* :: */[
                    /* PaddingLeft */Block.__(24, [/* Em */Block.__(1, [2.0])]),
                    /* :: */[
                      /* BorderRadius */Block.__(58, [/* Em */Block.__(1, [0.3])]),
                      /* :: */[
                        /* FontSize */Block.__(68, [/* Em */Block.__(1, [0.9])]),
                        /* :: */[
                          /* FontWeight */Block.__(70, [/* W400 */5]),
                          /* :: */[
                            /* FontFamily */Block.__(67, ["Helvetica Neue"]),
                            /* :: */[
                              /* BoxShadow */Block.__(48, ["rgba(67, 90, 111, 0.145) 0px 0px 0px 1px inset, rgba(67, 90, 111, 0.08) 0px -1px 1px 0px inset"]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var component = ReasonReact.statelessComponent("Button");

function make(onClick, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("button", {
                  className: buttonStyle,
                  onClick: onClick
                }, children);
    });
  return newrecord;
}

exports.buttonStyle = buttonStyle;
exports.component   = component;
exports.make        = make;
/* buttonStyle Not a pure module */
