// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                = require("bs-platform/lib/js/block.js");
var Curry                = require("bs-platform/lib/js/curry.js");
var React                = require("react");
var ReasonReact          = require("reason-react/src/ReasonReact.js");
var Js_primitive         = require("bs-platform/lib/js/js_primitive.js");
var Navbar$ReactTemplate = require("./navbar.bs.js");
var Director             = require("director/build/director");

var component = ReasonReact.reducerComponent("App");

function make(auth, fb, _) {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (param) {
      var reduce = param[/* reduce */1];
      var router = new Director.Router({
            "/": Curry._1(reduce, (function () {
                    return /* ShowAllRecipes */0;
                  }))
          });
      router.init("/");
      auth.onAuthStateChanged(Curry._1(reduce, (function (user) {
                  return /* AuthStateChanged */[(user == null) ? /* None */0 : [user]];
                })));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Navbar$ReactTemplate.make(self[/* state */2][/* user */1], auth, fb, /* array */[])), React.createElement("div", undefined, "hello world"));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* showing : AllRecipes */0,
              /* user */Js_primitive.null_undefined_to_opt(auth.currentUser)
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action) {
        return /* Update */Block.__(0, [/* record */[
                    /* showing */state[/* showing */0],
                    /* user */action[0]
                  ]]);
      } else {
        return /* Update */Block.__(0, [/* record */[
                    /* showing : AllRecipes */0,
                    /* user */state[/* user */1]
                  ]]);
      }
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
