// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var uuid = (function() {return Math.random().toString(16).slice(2)});

function eventValue($$event) {
  return $$event.target.value;
}

exports.uuid       = uuid;
exports.eventValue = eventValue;
/* uuid Not a pure module */
