// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Firebase  = require("firebase");
var Firestore = require("firebase/firestore");

var fb = Firebase.initializeApp({
      apiKey: "AIzaSyBKGuIOhz-JerBhCXe8Y-6kS05nU8bDVFM",
      authDomain: "fb-family-recipes.firebaseapp.com",
      databaseURL: "https://fb-family-recipes.firebaseio.com",
      projectId: "fb-family-recipes",
      storageBucket: "",
      messagingSenderId: "927755377339"
    });

exports.fb = fb;
/*  Not a pure module */
