// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                   = require("bs-platform/lib/js/block.js");
var Curry                   = require("bs-platform/lib/js/curry.js");
var React                   = require("react");
var ReasonReact             = require("reason-react/src/ReasonReact.js");
var Nice$ReactTemplate      = require("./Nice.bs.js");
var BaseUtils$ReactTemplate = require("./baseUtils.bs.js");

var title = Nice$ReactTemplate.css(/* :: */[
      /* FontWeight */Block.__(70, [/* Bold */1]),
      /* [] */0
    ]);

var Styles = /* module */[/* title */title];

function str(prim) {
  return prim;
}

var component = ReasonReact.reducerComponent("EditRecipe");

function make(_, _$1, _$2, _$3) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      return React.createElement("div", undefined, React.createElement("h1", {
                      className: title
                    }, "add recipe"), React.createElement("label", undefined, "Title"), React.createElement("input", {
                      id: "title",
                      value: param[/* state */2][/* title */0],
                      onChange: Curry._1(param[/* reduce */1], (function (evt) {
                              return /* SetTitle */Block.__(0, [BaseUtils$ReactTemplate.eventValue(evt)]);
                            }))
                    }));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[
              /* title */"",
              /* description */"",
              /* content */""
            ];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      switch (action.tag | 0) {
        case 0 : 
            return /* Update */Block.__(0, [/* record */[
                        /* title */action[0],
                        /* description */state[/* description */1],
                        /* content */state[/* content */2]
                      ]]);
        case 1 : 
            return /* Update */Block.__(0, [/* record */[
                        /* title */state[/* title */0],
                        /* description */action[0],
                        /* content */state[/* content */2]
                      ]]);
        case 2 : 
            return /* Update */Block.__(0, [/* record */[
                        /* title */state[/* title */0],
                        /* description */state[/* description */1],
                        /* content */action[0]
                      ]]);
        
      }
    });
  return newrecord;
}

exports.Styles    = Styles;
exports.str       = str;
exports.component = component;
exports.make      = make;
/* title Not a pure module */
