// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe        = require("reason-react/src/ReactDOMRe.js");
var ReasonReact       = require("reason-react/src/ReasonReact.js");
var DB$ReactTemplate  = require("./DB.bs.js");
var App$ReactTemplate = require("./app.bs.js");

DB$ReactTemplate.fb.firestore().enablePersistence().catch((function (err) {
          console.log("error", err);
          return Promise.resolve(/* () */0);
        })).then((function () {
        ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, App$ReactTemplate.make(DB$ReactTemplate.fb.auth(), DB$ReactTemplate.fb, /* array */[])), "index");
        return Promise.resolve(/* () */0);
      }));

var fb = DB$ReactTemplate.fb;

exports.fb = fb;
/*  Not a pure module */
