// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean = require("bs-platform/lib/js/js_boolean.js");

function blank(id, authorId) {
  var now = Date.now();
  var empty = { };
  return {
          id: id,
          authorId: authorId,
          collaborators: empty,
          isPrivate: Js_boolean.to_js_boolean(/* false */0),
          title: "",
          description: "",
          titleSearch: empty,
          created: now,
          updated: now,
          imageUrl: null,
          tags: empty,
          source: null,
          instructions: ""
        };
}

var Recipe = /* module */[
  /* name */"recipes",
  /* blank */blank
];

exports.Recipe = Recipe;
/* No side effect */
