// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                = require("bs-platform/lib/js/block.js");
var Curry                = require("bs-platform/lib/js/curry.js");
var React                = require("react");
var ReasonReact          = require("reason-react/src/ReasonReact.js");
var Nice$ReactTemplate   = require("./Nice.bs.js");
var Util$ReactTemplate   = require("./util.bs.js");
var Button$ReactTemplate = require("./UI/button.bs.js");

var className = Nice$ReactTemplate.css(/* :: */[
      /* Display */Block.__(0, [/* Flex */4]),
      /* :: */[
        /* Color */Block.__(66, [/* Red */119]),
        /* [] */0
      ]
    ]);

var component = ReasonReact.statelessComponent("Navbar");

function make(user, auth, _, _$1) {
  var onClick = function () {
    auth.signInWithEmailAndPassword("ben.mcmahen@gmail.com", "awesomepassword").then((function (user) {
              console.log(user);
              return Promise.resolve(/* () */0);
            })).catch((function (err) {
            console.log(err);
            return Promise.resolve(/* () */0);
          }));
    return /* () */0;
  };
  var signOut = function () {
    auth.signOut();
    return /* () */0;
  };
  var loginWithGoogle = function () {
    var getProvider = (
      function () {
        const firebase = require('firebase');
        return new firebase.auth.GoogleAuthProvider();
      }
    );
    auth.signInWithPopup(Curry._1(getProvider, /* () */0)).then((function (loginResult) {
              console.log(loginResult);
              return Promise.resolve(/* () */0);
            })).catch((function (err) {
            console.log(err);
            return Promise.resolve(/* () */0);
          }));
    return /* () */0;
  };
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function () {
      console.log(auth);
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "Navbar"
                }, user ? ReasonReact.element(/* None */0, /* None */0, Button$ReactTemplate.make(signOut, Util$ReactTemplate.str("Sign out"))) : React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Button$ReactTemplate.make(loginWithGoogle, "Login with Google")), React.createElement("button", {
                            onClick: onClick
                          }, "Login with email")));
    });
  return newrecord;
}

exports.className = className;
exports.component = component;
exports.make      = make;
/* className Not a pure module */
